"""Application constants for the synthesizer."""

SCR_WIDTH, SCR_HEIGHT = 1920, 1080
SAMPLE_RATE = 44100
MIXER_SIZE = -16
CHANNEL = 1
BUFFER_SIZE = 512
DURATION = 10.0

WHITE_KEY_WIDTH = 80
WHITE_KEY_HEIGHT = 450
BLACK_KEY_WIDTH = 40
BLACK_KEY_HEIGHT = 300
KEYBOARD_WIDTH = 50
KEYBOARD_POS_X = SCR_WIDTH / 2 - (20 * WHITE_KEY_WIDTH + 2 * KEYBOARD_WIDTH) / 2
KEYBOARD_POS_Y = SCR_HEIGHT - (WHITE_KEY_HEIGHT + KEYBOARD_WIDTH)

OSCILLATOR_POS_Y = 50
OSCILLATOR_WIDTH = 100
OSCILLATOR_HEIGHT = 490

SLIDER_WIDTH = 60
SLIDER_HEIGHT = 200
SLIDERS_POS_X = 25
SLIDERS_POS_Y = 25

FILTER_WIDTH = 320
FILTER_HEIDHT = 237

SPEAKER_WIDTH = 200
SPEAKER_HEIGHT = 200
SPEAKER_POS_X = SCR_WIDTH / 2 - SPEAKER_WIDTH / 2
SPEAKER_POS_Y = OSCILLATOR_POS_Y - 5

ENVELOPE_POS_X = SPEAKER_POS_X + SPEAKER_WIDTH + 16
ENVELOPE_POS_Y = OSCILLATOR_POS_Y
ENVELOPE_WIDTH = 310
ENVELOPE_HEIGHT = FILTER_HEIDHT

OSCILLOSCOPE_POS_X = ENVELOPE_POS_X + ENVELOPE_WIDTH + 20
OSCILLOSCOPE_POS_Y = ENVELOPE_POS_Y
OSCILLOSCOPE_HEIGHT = 300

OCTAVEDISPLAY_POS_X = 10
OCTAVEDISPLAY_POS_Y = 25
LED_RADIUS = 25
OCTAVE_MAX = 2
OCTAVE_MIN = -2
NOTE_MAX = 88
NUM_CHANNEL = NOTE_MAX + OCTAVE_MAX * 12 + 1
HARMONIC = 10
